Token=90091783812067009:0:3fvD5mz52a3HBPx7bOUhp8ATZo28Kz
URI=wss://d1.nandbox.net:5020/nandbox/api/
DownloadServer=https://d1.nandbox.net:5020/nandbox/download/
UploadServer=https://d1.nandbox.net:5020/nandbox/upload/