name: CI

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  call-build:
    uses: nandbox-extensions/shared-ci/.github/workflows/build-ghcr.yml@main
    secrets:
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
